from __future__ import annotations

import os
import re
import subprocess
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from uuid import UUID

from docx import Document
from docx.enum.text import WD_COLOR_INDEX
from docx2pdf import convert
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import joinedload

from app.models.export import Export
from app.models.requirement import Requirement

EXPORT_ROOT = Path(__file__).resolve().parents[2] / "exports"
REQ_ID_PATTERN = re.compile(r"^REQ-\d+$")


def _today_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _history_row_from_docx(docx_path: str, version: int) -> tuple[str, str] | None:
    if not os.path.exists(docx_path):
        return None

    try:
        doc = Document(docx_path)
    except Exception:
        return None

    target_version = f"{version}.0"
    for table in doc.tables:
        for row in table.rows[1:]:
            cells = [cell.text.strip() for cell in row.cells]
            if len(cells) < 3:
                continue
            if cells[0] == target_version:
                return (cells[1], cells[2])
    return None


def load_previous_requirements(previous_docx_path: str) -> dict[str, str]:
    if not os.path.exists(previous_docx_path):
        return {}

    try:
        doc = Document(previous_docx_path)
    except Exception:
        return {}

    req_map: dict[str, str] = {}
    paragraphs = [p.text.strip() for p in doc.paragraphs]

    for index, text in enumerate(paragraphs):
        if not REQ_ID_PATTERN.match(text):
            continue

        statement = ""
        for next_text in paragraphs[index + 1 :]:
            if not next_text:
                continue
            if REQ_ID_PATTERN.match(next_text):
                break
            if next_text.startswith("Source:") or next_text.startswith("Validation:"):
                continue
            statement = next_text
            break

        req_map[text] = statement

    return req_map


def build_change_description(added: set[str], removed: set[str], updated: set[str]) -> str:
    parts: list[str] = []

    if added:
        parts.append(f"Added {len(added)} requirement(s)")
    if removed:
        parts.append(f"Removed {len(removed)} requirement(s)")
    if updated:
        parts.append(f"Updated {len(updated)} requirement(s)")

    return "; ".join(parts) if parts else "No changes"


def _add_placeholder_paragraph(doc: Document, text: str) -> None:
    paragraph = doc.add_paragraph(text)
    for run in paragraph.runs:
        run.italic = True
        run.font.highlight_color = WD_COLOR_INDEX.GRAY_25


def _first_source_identifier(requirement: Requirement) -> str:
    if not requirement.traceability_links:
        return "N/A"

    best_link = sorted(requirement.traceability_links, key=lambda link: link.similarity_score, reverse=True)[0]
    if best_link.document_section is None or not best_link.document_section.source_identifier:
        return "N/A"
    return best_link.document_section.source_identifier


def _validation_result(requirement: Requirement) -> str:
    if requirement.validation_report is None:
        return "N/A"
    return requirement.validation_report.result


def _build_docx(
    output_path: str,
    session_name: str,
    requirements: list[Requirement],
    version: int,
    change_description: str,
    historical_rows: list[tuple[int, str, str]],
) -> None:
    doc = Document()

    doc.add_heading("Software Requirements Specification", 0)
    doc.add_paragraph(f"Project: {session_name}")
    doc.add_paragraph(f"Generated by SpecAgent on {datetime.now(timezone.utc).isoformat()}")
    doc.add_paragraph(f"Document Version: {version}.0")

    doc.add_heading("Revision History", level=1)
    table = doc.add_table(rows=1, cols=3)
    table.style = "Table Grid"

    header_cells = table.rows[0].cells
    header_cells[0].text = "Version"
    header_cells[1].text = "Date"
    header_cells[2].text = "Description of Changes"
    for header_cell in header_cells:
        for paragraph in header_cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True

    for version_number, date_str, description in historical_rows:
        row = table.add_row().cells
        row[0].text = f"{version_number}.0"
        row[1].text = date_str
        row[2].text = description

    current_row = table.add_row().cells
    current_row[0].text = f"{version}.0"
    current_row[1].text = _today_str()
    current_row[2].text = change_description

    doc.add_heading("Notice", level=1)
    doc.add_paragraph(
        "This SRS was generated by SpecAgent from an uploaded requirements document. "
        "Sections 3 and 4 contain AI-extracted and user-approved requirements. "
        "All other sections require manual completion by the project team."
    )

    doc.add_heading("1. Introduction", level=1)
    _add_placeholder_paragraph(doc, "1.1 Purpose - [To be completed by project team]")
    _add_placeholder_paragraph(doc, "1.2 Scope - [To be completed by project team]")
    _add_placeholder_paragraph(doc, "1.3 Definitions - [To be completed by project team]")

    doc.add_heading("2. Overall Description", level=1)
    _add_placeholder_paragraph(doc, "2.1 Product Perspective - [To be completed by project team]")
    _add_placeholder_paragraph(doc, "2.2 Operating Environment - [To be completed by project team]")

    doc.add_heading("3. Functional Requirements", level=1)
    functional = [
        requirement
        for requirement in requirements
        if requirement.classification is not None and requirement.classification.type == "functional"
    ]

    for requirement in sorted(functional, key=lambda req: req.req_id):
        doc.add_heading(requirement.req_id, level=2)
        doc.add_paragraph(requirement.statement)
        doc.add_paragraph(f"Source: {_first_source_identifier(requirement)}")
        doc.add_paragraph(f"Validation: {_validation_result(requirement)}")

    doc.add_heading("4. Non-Functional Requirements", level=1)
    non_functional = [
        requirement
        for requirement in requirements
        if requirement.classification is not None and requirement.classification.type == "non-functional"
    ]

    grouped: dict[str, list[Requirement]] = defaultdict(list)
    for requirement in non_functional:
        grouped[(requirement.classification.sub_category or "general").strip().lower()].append(requirement)

    for sub_category in sorted(grouped.keys()):
        doc.add_heading(sub_category.title(), level=2)
        for requirement in sorted(grouped[sub_category], key=lambda req: req.req_id):
            doc.add_heading(requirement.req_id, level=3)
            doc.add_paragraph(requirement.statement)

    doc.add_heading("5. System Constraints", level=1)
    doc.add_paragraph("[To be completed by project team]")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc.save(output_path)


async def _latest_docx_export(session_id: UUID, db: AsyncSession) -> Export | None:
    result = await db.execute(
        select(Export)
        .where(Export.session_id == session_id, Export.format == "docx")
        .order_by(Export.version.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


async def _docx_history_rows(session_id: UUID, db: AsyncSession) -> list[tuple[int, str, str]]:
    result = await db.execute(
        select(Export)
        .where(Export.session_id == session_id, Export.format == "docx")
        .order_by(Export.version.asc())
    )
    exports = list(result.scalars().all())

    history_rows: list[tuple[int, str, str]] = []
    for export_record in exports:
        parsed = _history_row_from_docx(export_record.file_path, export_record.version)
        if parsed is not None:
            date_str, description = parsed
        else:
            date_str = export_record.created_at.strftime("%Y-%m-%d")
            description = "Export generated"
        history_rows.append((export_record.version, date_str, description))

    return history_rows


def _current_requirements_map(requirements: Iterable[Requirement]) -> dict[str, str]:
    return {requirement.req_id: requirement.statement for requirement in requirements}


async def generate_srs_docx(
    session_id: UUID,
    session_name: str,
    requirements: list[Requirement],
    db: AsyncSession,
) -> tuple[str, int, str]:
    existing_export = await _latest_docx_export(session_id, db)

    if existing_export is not None:
        previous_map = load_previous_requirements(existing_export.file_path)
        current_map = _current_requirements_map(requirements)

        previous_req_ids = set(previous_map.keys())
        current_req_ids = set(current_map.keys())

        added = current_req_ids - previous_req_ids
        removed = previous_req_ids - current_req_ids
        updated = {
            req_id
            for req_id in (current_req_ids & previous_req_ids)
            if previous_map.get(req_id, "") != current_map.get(req_id, "")
        }

        change_description = build_change_description(added, removed, updated)
        new_version = existing_export.version + 1
    else:
        change_description = "Initial extraction and export"
        new_version = 1

    dir_path = EXPORT_ROOT / str(session_id)
    file_path = str(dir_path / f"SRS_v{new_version}.docx")

    historical_rows = await _docx_history_rows(session_id, db)

    _build_docx(
        output_path=file_path,
        session_name=session_name,
        requirements=requirements,
        version=new_version,
        change_description=change_description,
        historical_rows=historical_rows,
    )

    export_record = Export(
        session_id=session_id,
        format="docx",
        file_path=file_path,
        version=new_version,
        parent_id=existing_export.id if existing_export else None,
    )
    db.add(export_record)
    await db.commit()

    return file_path, new_version, change_description


async def generate_srs_pdf(
    session_id: UUID,
    session_name: str,
    requirements: list[Requirement],
    db: AsyncSession,
) -> tuple[str, int, str]:
    existing_export = await _latest_docx_export(session_id, db)

    if existing_export is not None:
        version = existing_export.version
        previous_map = load_previous_requirements(existing_export.file_path)
        current_map = _current_requirements_map(requirements)
        previous_req_ids = set(previous_map.keys())
        current_req_ids = set(current_map.keys())
        added = current_req_ids - previous_req_ids
        removed = previous_req_ids - current_req_ids
        updated = {
            req_id
            for req_id in (current_req_ids & previous_req_ids)
            if previous_map.get(req_id, "") != current_map.get(req_id, "")
        }
        change_description = build_change_description(added, removed, updated)
    else:
        version = 1
        change_description = "Initial extraction and export"

    dir_path = EXPORT_ROOT / str(session_id)
    os.makedirs(dir_path, exist_ok=True)

    temp_docx_path = str(dir_path / f"SRS_v{version}_temp.docx")
    pdf_path = str(dir_path / f"SRS_v{version}.pdf")

    historical_rows = await _docx_history_rows(session_id, db)

    _build_docx(
        output_path=temp_docx_path,
        session_name=session_name,
        requirements=requirements,
        version=version,
        change_description=change_description,
        historical_rows=historical_rows,
    )

    try:
        convert(temp_docx_path, pdf_path)
    except Exception:
        subprocess.run(
            [
                "libreoffice",
                "--headless",
                "--convert-to",
                "pdf",
                "--outdir",
                str(dir_path),
                temp_docx_path,
            ],
            check=True,
        )

    if os.path.exists(temp_docx_path):
        os.remove(temp_docx_path)

    export_record = Export(
        session_id=session_id,
        format="pdf",
        file_path=pdf_path,
        version=version,
        parent_id=existing_export.id if existing_export else None,
    )
    db.add(export_record)
    await db.commit()

    return pdf_path, version, change_description


def _build_rtm_docx(
    output_path: str,
    session_name: str,
    rows: list[dict[str, object]],
) -> None:
    
    doc = Document()

    doc.add_heading("Requirements Traceability Matrix", 0)
    doc.add_paragraph(f"Project: {session_name}")
    doc.add_paragraph(f"Generated by SpecAgent on {datetime.now(timezone.utc).isoformat()}")
    doc.add_paragraph(f"Total Requirements: {len(rows)}")

    if not rows:
        doc.add_paragraph("No requirements to display.")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        doc.save(output_path)
        return

    table = doc.add_table(rows=1, cols=7)
    table.style = "Table Grid"

    header_cells = table.rows[0].cells
    headers = ["REQ-ID", "Statement", "Type", "Sub-Category", "Validation", "Finalization", "Sources"]
    for i, header_text in enumerate(headers):
        header_cells[i].text = header_text
        for paragraph in header_cells[i].paragraphs:
            for run in paragraph.runs:
                run.bold = True

    for row_data in rows:
        row = table.add_row().cells
        row[0].text = str(row_data.get("req_id", ""))
        row[1].text = str(row_data.get("statement", ""))
        row[2].text = str(row_data.get("type", ""))
        row[3].text = str(row_data.get("sub_category", "") or "")
        row[4].text = str(row_data.get("validation_result", "") or "")
        row[5].text = str(row_data.get("finalization_status", ""))

        sources = row_data.get("sources", [])
        sources_text = ""
        if isinstance(sources, list):
            for src in sources:
                if isinstance(src, dict):
                    src_id = src.get("source_identifier", "")
                    score = src.get("similarity_score", 0)
                    if src_id:
                        sources_text += f"{src_id} ({score:.2f})\n"
        row[6].text = sources_text.strip()

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    try:
        doc.save(output_path)
    except Exception as save_err:
        raise


async def generate_rtm_pdf(
    session_id: UUID,
    session_name: str,
    rows: list[dict[str, object]],
    db: AsyncSession,
) -> str:
    dir_path = EXPORT_ROOT / str(session_id)
    os.makedirs(dir_path, exist_ok=True)

    temp_docx_path = str(dir_path / "RTM_temp.docx")
    pdf_path = str(dir_path / "RTM.pdf")
    temp_pdf_path = str(dir_path / "RTM_temp.pdf")

    _build_rtm_docx(
        output_path=temp_docx_path,
        session_name=session_name,
        rows=rows,
    )
    
    # CRITICAL CHECK
    if not os.path.exists(temp_docx_path):
        raise RuntimeError(f"RTM DOCX file was not created at {temp_docx_path}")
    
    try:
        result = subprocess.run(
            [
                "/Applications/LibreOffice.app/Contents/MacOS/soffice",
                "--headless",
                "--convert-to",
                "pdf",
                "--outdir",
                str(dir_path),
                temp_docx_path,
            ],
            check=True,
            capture_output=True,
            text=True,
        )

    except subprocess.CalledProcessError as sub_err:
        raise
            
    if os.path.exists(temp_pdf_path):
        os.rename(temp_pdf_path, pdf_path)
    
    if not os.path.exists(pdf_path):
        raise RuntimeError(f"RTM PDF file was not created at {pdf_path}")

    if os.path.exists(temp_docx_path):
        os.remove(temp_docx_path)

    return pdf_path
