"""add source metadata to document_section

Revision ID: c0f29e862366
Revises: 3a7ec719415b
Create Date: 2026-04-23 19:37:59.813425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f29e862366'
down_revision: Union[str, Sequence[str], None] = '3a7ec719415b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_section', sa.Column('source_page', sa.Integer(), nullable=True))
    op.add_column('document_section', sa.Column('source_page_end', sa.Integer(), nullable=True))
    op.add_column('document_section', sa.Column('source_identifier', sa.Text(), nullable=True))
    op.add_column('document_section', sa.Column('document_type', sa.Text(), nullable=True, comment='Valid values: pdf | docx | txt | email'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_section', 'document_type')
    op.drop_column('document_section', 'source_identifier')
    op.drop_column('document_section', 'source_page_end')
    op.drop_column('document_section', 'source_page')
    # ### end Alembic commands ###
